apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: orders
  labels:
    app: orders
spec:
  to:
    kind: Service
    name: orders
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow