apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: orders-pipeline
spec:
  params:
    - description: The git repository URL to clone from
      name: GIT_REPO
      type: string
    - description: The reference (branch or ref)
      name: GIT_REF
      type: string
  tasks:
    - name: git-clone
      params:
        - name: CRT_FILENAME
          value: ca-bundle.crt
        - name: HTTP_PROXY
          value: ""
        - name: HTTPS_PROXY
          value: ""
        - name: NO_PROXY
          value: ""
        - name: SUBDIRECTORY
          value: ""
        - name: USER_HOME
          value: /home/git
        - name: DELETE_EXISTING
          value: "true"
        - name: VERBOSE
          value: "false"
        - name: SSL_VERIFY
          value: "true"
        - name: URL
          value: $(params.GIT_REPO)
        - name: REVISION
          value: $(params.GIT_REF)
        - name: REFSPEC
          value: ""
        - name: SUBMODULES
          value: "true"
        - name: DEPTH
          value: "1"
        - name: SPARSE_CHECKOUT_DIRECTORIES
          value: ""
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: output
          workspace: pipeline-workspace

    - name: unit-test
      taskRef:
        name: pytest
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: lint
      taskRef:
        name: pylint
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: build-image
      taskRef:
        name: build-and-push-image
      runAfter:
        - unit-test
        - lint
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/orders:latest
        - name: CONTEXT
          value: .
      workspaces:
        - name: source
          workspace: pipeline-workspace

  workspaces:
    - name: pipeline-workspace